### ISSUE TITLE
Immediate error upon analysis 

### ISSUE THREAD

**Issue by rmacatee** [peclayson/ERA_Toolbox#17]
Hello Dr. Clayson,

   I am using version 0.4.7 of the ERP Reliability Analysis Toolbox.  I am using Matlab 2015a.

I have appropriately long formatted data that I attempt to analyze using the toolbox but almost immediately get an error after pressing 'Analyze' - the error is posted below.  My columns are: SubjID for participant ID, caps_ptsd_dx for diagnostic group (0=NoPTSD,1=PTSD), TrialType (1=anger,2=fear,3=happy,4=shapes) for the condition, and LPPAmp for the single-trial mean amplitudes.  Before clicking 'Analyze', I made sure that all columns were accurate and the group and trialType codes were selected.

Error using ismember (line 79)
Invalid input. Valid flags are 'rows', 'legacy', 'R2012a'.

Error in era_loadfile (line 312)
            dataout = dataout(ismember(...

Error in era_startproc>era_exec (line 1180)
era_data.proc.data = era_loadfile('era_prefs',era_prefs,...
 
Error while evaluating DestroyedObject Callback

Thank you for your help!

-Richard Macatee

**Comment by peclayson** [comment]
Hi Richard,

First off, sorry for the slow response. I must have missed the email from Github letting me know that there was a new issue.

I wasn't able to replicate your problem exactly. But I did find a bug when trying to load a file with numeric variables for group membership. I pushed a commit just now that fixes this problem (d169760931aacad3168521d94e985f20a770e945). I don't know if this means it will run for you. If you still get that bug, let me know. I may need you to send me a snippet of data to see if I can replicate it.

When I googled your problem, it looked like it may be an issue with your Matlab version, but I'll download 2015a right now to see if that's the case. I wouldn't think that the Matlab version would be the problem since you are using a version more recent than 2012 when the change was made to the ismember function. I'll let you know what happens when I try using 2015a. I should be able to check it out this afternoon.

Keep me posted if you are able to try the new commit.

Thanks,
Peter

**Comment by peclayson** [comment]
Oh, in order download the new code, you'll need to download or clone the [master](https://github.com/peclayson/ERA_Toolbox). I haven't pushed a new release with this fix, yet.

**Comment by peclayson** [comment]
I also found that there was the same problem happening for some types of numeric events. I tested the most recent commit in 2015a and 2017a, and I didn't have any problems. Let me know if this fix works for you. Good luck!

Thanks,
Peter

**Comment by rmacatee** [comment]
Hey Peter,

   Thanks!  I downloaded the new master and overwrote my old one.  Unfortunately, I'm still getting the same error.  I thought it would be helpful for you to see the data so I've attached a sample of it to this message to see if you can recreate the error.

   Really appreciate the help!
[DataSample.xlsx](https://github.com/peclayson/ERA_Toolbox/files/1929719/DataSample.xlsx)


-Ricky

**Comment by peclayson** [comment]
Hey Ricky,

I was just wondering whether you had any success. Let me know if you need any more help.

Peter

**Comment by rmacatee** [comment]
Hey Peter,

   Sorry with the delay - been swamped lately.  I've tried running it on just the sample I sent you and still get the same error.  I'll try re-downloading the master and try again and let you know what happens tomorrow.

-Ricky

**Comment by rmacatee** [comment]
Hey Peter,

  I re-downloaded and installed the master - unfortunately, the sample still produces the same error (reproduced below):

Error using ismember (line 79)
Invalid input. Valid flags are 'rows', 'legacy', 'R2012a'.

Error in era_loadfile (line 348)
                dataout = dataout(ismember(...

Error in era_startproc>era_exec (line 1180)
era_data.proc.data = era_loadfile('era_prefs',era_prefs,...
 
Error while evaluating DestroyedObject Callback


One thing I noticed during the toolkit's start up is that I get the message "Warning: Installed MatlabProcessManager version is newer than the version tested for the Toolbox.  Toolbox may not work properly as a result."  Should I try getting an older version of the MatlabProcessManager?  I'm reluctant to change my version of Matlab because there are some utilities I rely upon that don't work in versions newer than 2015a, so I'm pretty stuck with this version at the moment.

-Ricky

**Comment by peclayson** [comment]
Hi Ricky,

Ok, I tried to replicate your issue on a Windows machine, but it uses Windows 10. I wasn't able to replicate the problem. I made one more tweak that might help you (you'll have to redownload the master again). 

I'll have access to a Windows 7 machine on Monday, and I'll try to replicate your problem then.

Sorry this is taking so much work... Fingers crossed!

Thanks,
Peter

**Comment by rmacatee** [comment]
Hey Peter,

   I re-downloaded the master and, unfortunately, I got the same error.  Just wanted to let you know!

-Ricky

**Comment by peclayson** [comment]
Hi Ricky,

Unfortunately, I no longer have access to a Windows machine that runs Windows 7. And, I'm unable to replicate the error, so I'm a bit stumped as to what to do. If you're familiar with Matlab, I could walk you through some debugging steps, if you're interested. I think that might be our best shot.

Thanks,
Peter

**Comment by rmacatee** [comment]
Hey Peter,

   I'll be moving shortly and will have access to additional Matlab versions in addition to the older version I need now for other utilities.  Since it's not super time sensitive, I'll see if it works first on a newer version of Matlab and then circle back to this bug if necessary.

   Thanks for the help!

-Ricky

**Comment by peclayson** [comment]
Sounds good. Good luck!

Peter
